name: Java CI with Maven

on:
  push:
    branches: [ "containers" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run tests
        run: mvn clean test -Dtest=ru.inno.selenium.pageobject.sampleapp.SampleAppTest --file pom.xml
      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          allure_results: allure-results